---
###############################################################################
# LDAP Provider Workflow
###############################################################################

###############################################################################
# Establish LDAP Connectivity
###############################################################################
- import_tasks: connect.yml

###############################################################################
# Authenticate to Active Directory
###############################################################################
- import_tasks: authenticate.yml

###############################################################################
# Publish LDAP Connection Facts
###############################################################################
- import_tasks: publish.yml