---
###############################################################################
# Role        : directory_connection
# Provider    : LDAP
# Description : LDAP Provider Entry Point
###############################################################################

- import_tasks: ldap/main.yml