---
###############################################################################
# Ansible Collection Requirements
# Used by Ansible Builder when creating the Execution Environment.
###############################################################################

collections:

  ###########################################################################
  # Active Directory
  ###########################################################################

  - name: community.general

  - name: microsoft.ad

  ###########################################################################
  # AWS
  ###########################################################################

  - name: amazon.aws

  - name: community.aws

  ###########################################################################
  # Windows
  ###########################################################################

  - name: ansible.windows