---
###############################################################################
# Build Identity Catalog
###############################################################################

###############################################################################
# Collect Active Directory Users
###############################################################################
- import_tasks: users.yml

###############################################################################
# Normalize User Objects
###############################################################################
- import_tasks: normalize_users.yml

###############################################################################
# Collect Active Directory Service Accounts
###############################################################################
- import_tasks: service_accounts.yml

###############################################################################
# Normalize Service Accounts
###############################################################################
- import_tasks: normalize_service_accounts.yml

###############################################################################
# Collect Active Directory Groups
###############################################################################
- import_tasks: groups.yml

###############################################################################
# Collect Organizational Units
###############################################################################
- import_tasks: ous.yml

###############################################################################
# Normalize Organizational Units
###############################################################################
- import_tasks: normalize_ous.yml

###############################################################################
# Publish Identity Catalog
###############################################################################
- import_tasks: publish.yml


