---
###############################################################################
# Normalize Service Accounts
###############################################################################

- name: Initialize normalized service account catalog
  ansible.builtin.set_fact:
    normalized_service_accounts: []

- name: Normalize service accounts
  ansible.builtin.set_fact:

    normalized_service_accounts: >-
      {{
        normalized_service_accounts +
        [
          {
            'type'         : 'service_account',
            'username'     : item.sAMAccountName | default(''),
            'display_name' : item.cn | default(''),
            'given_name'   : item.givenName | default(''),
            'surname'      : item.sn | default(''),
            'upn'          : item.userPrincipalName | default(''),
            'dn'           : item.distinguishedName | default(''),
            'groups'       : (
                                item.memberOf is string
                                | ternary([item.memberOf], item.memberOf | default([]))
                              )
          }
        ]
      }}

  loop: "{{ ldap_service_accounts.results }}"