---
###############################################################################
# Role        : identity_catalog
# Task        : service_accounts
# Description : Collect Active Directory service accounts.
###############################################################################

- name: Query Active Directory service accounts
  community.general.ldap_search:

    server_uri: "ldap://{{ directory_connection.host }}"

    bind_dn: "{{ directory_credentials.username }}"

    bind_pw: "{{ directory_credentials.password }}"

    dn: "{{ directory_connection.search_base }}"

    scope: subordinate

    filter: "{{ identity_catalog_filters.service_accounts }}"

    attrs:
      - cn
      - sAMAccountName
      - userPrincipalName
      - distinguishedName
      - givenName
      - sn
      - memberOf
      - objectGUID
      - objectSid

  register: ldap_service_accounts