---
- name: Test Credential Manager
  hosts: localhost
  gather_facts: false

  vars:
    credential_backend: plaintext
    directory_username: Administrator
    directory_password: Password123!

  tasks:

  - name: Execute credential manager
    include_role:
      name: credential_manager

  - debug:
      var: directory_credentials.username