---
###############################################################################
# Role        : directory_connection
# File        : vars/main.yml
# Description : Reserved for static role variables.
###############################################################################